### PR TITLE
use correct name for stage option

### LINKED ISSUE #16: Deprecation warning on build
When building a brand new application the following deprecation warning will show up.

> Serverless: Deprecation warning: "provider.stage" is not accessible (configured behind variables which cannot be resolved at this stage).
            Starting with next major release, this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to this behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER

### Reproduction

run the following steps from your favourite command line tool

```
npx create-nx-workspace --name=sample --preset=empty --nx-cloud=false
cd sample
npm i
npm i -D @ns3/nx-serverless
nx generate @ns3/nx-serverless:app my-app-name
npm run build my-app-name
```

### PR DESCRIPTION
**Pull request by MelvinVermeer**
Fixes #16

### CODE REVIEW

**Comment by Bielik20** [comment]
Hmm, it was actually done intentionally this way, because `serverless` will use `stage` option in many places so that you cannot modify it. By naming it something different I get more freedom what I can do with it.

But perhaps this is not a case for most users. Can you change commit to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)? This should be a `fix`.
How were you able to commit with that message? I have set up git hooks that inform you that this commit message is not correct.

I will look into those deprecation warnings some time next week (I hope) and will merge it if i really helps ;)

**Comment by MelvinVermeer** [comment]
Commit message is changed now, thanks for looking into it

**Comment by Bielik20** [comment]
Hmm, I see that deprecation is part of larger rework on serverless side.
I will part this PR for now. In future I will try at work more complex setups, if they work like that now then I will merge it.
If additional steps are required I will comment here.

**Comment by Bielik20** [comment]
Will be done in https://github.com/Bielik20/nx-plugins/pull/36

**Pull request closed without merging**
